name: sol_site
dependencies:
- openssl
- pip
- python=3
- readline
- setuptools
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - webassets==0.12.1
  - cssutils==1.0.2
  - jsmin==2.2.1
  - blinker==1.4
  - docutils==0.12
  - ecdsa==0.13
  - fabric3==1.10.2.post1
  - feedgenerator==1.7
  - jinja2==2.8
  - markdown==2.6.5
  - markupsafe==0.23
  - paramiko==1.16.0
  - pelican==3.6.3
  - pycrypto==2.6.1
  - pygments==2.0.2
  - python-dateutil==2.4.2
  - pytz==2015.7
  - pyyaml==3.11
  - six==1.10.0
  - unidecode==0.4.18

