name: sol_site
dependencies:
- openssl=1.0.2d=0
- pip
- python=3.4.3=2
- readline=6.2=2
- setuptools=18.5=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - blinker==1.4
  - docutils==0.12
  - ecdsa==0.13
  - fabric3==1.10.2.post1
  - feedgenerator==1.7
  - ghp-import==0.4.1
  - jinja2==2.8
  - markdown==2.6.5
  - markupsafe==0.23
  - paramiko==1.16.0
  - pelican==3.6.3
  - pycrypto==2.6.1
  - pygments==2.0.2
  - python-dateutil==2.4.2
  - pytz==2015.7
  - pyyaml==3.11
  - six==1.10.0
  - unidecode==0.4.18

